---
- hosts: localhost
  tasks:
  - name: check apt update
    action: apt
    args:
      name: python-pip
      state: present
      update_cache: true
    register: check_apt_update
    retries: 3
  - debug:
      msg: 'Please check your `sudo apt update` status, make sure it has a non-zero exits'
    failed_when: check_apt_update is failed
    when: check_apt_update is failed
