---
- hosts: localhost
  tasks:
  - name: check apt update
    command: apt-get update
    register: check_apt_update
    become: yes
    retries: 3
  - debug:
    var: check_apt_update
  - debug:
      msg: 'Please check your `sudo apt update` status, make sure it has a non-zero exits'
    failed_when: check_apt_update is failed
    when: check_apt_update is failed
